### ISSUE TITLE
Please support Java8.

### ISSUE THREAD

**Issue by ViToni** [jonas-jonas/eclipse-dart#26]
The build fails on Java8 due to usage of `InputStream.transferTo()` and `Optional.ifPresentOrElse()`:

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.3.0:compile (default-compile) on project org.eclipse.dartboard: Compilation failure: Compilation failure:
[ERROR] Z:\git\eclipse-dart\org.eclipse.dartboard\src\org\eclipse\dartboard\launch\console\DartConsoleFactory.java:[44]
[ERROR]         inputStream.transferTo(outputSteam);
[ERROR]                     ^^^^^^^^^^
[ERROR] The method transferTo(IOConsoleOutputStream) is undefined for the type InputStream
[ERROR] Z:\git\eclipse-dart\org.eclipse.dartboard\src\org\eclipse\dartboard\preference\DartPreferencePage.java:[86]
[ERROR]         optionalVersion.ifPresentOrElse((version) -> {
[ERROR]                         ^^^^^^^^^^^^^^^
[ERROR] The method ifPresentOrElse((<no type> version) -> {}, () -> {}) is undefined for the type Optional<String>
```

**Comment by vogella** [comment]
We plan to use Java 11, can you upgrade your Java version?

Victor Toni <notifications@github.com> schrieb am Mo., 27. Mai 2019, 12:20:

**Comment by ViToni** [comment]
Unfortunately "we" are somehow fixed on Java8. Just wanted to start experimenting Dart a bit...

**Comment by jonas-jonas** [comment]
We weren't really aware of anyone using this project with Java 8. So our deliberate decision to use Java 11 was based on that. We will reevaluate the situation based on your request.

I guess it wouldn't hurt us much to also support Java 8 again. I will update you in this issue once we decided and added the version support back.

**Comment by jonas-jonas** [comment]
We decided to use Java 8 again. Since we are currently undergoing a move to the Eclipse Foundation, further work will be done in a private repository. I will notify you once we finished the move.

**Comment by jonas-jonas** [comment]
Just as a heads up, we moved the repository to the eclipse foundation and the plugin should now work with java 8. 

Be aware, the plugin is very early in its development phase and not ready for "production" use yet. Also tested only on Linux (Ubuntu & Fedora). So anything else _might_ work, but is very likely not working.
